jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Tests
        run: npm test

  job2:
    needs: job1
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying after Job1 success"

  pr-opened:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint the code
        run: npm run lint
        
  run-on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Deploy
        run: echo "Build and deploy on push"
