name: this demo is to get ON section in github 

on: 
  push: 
    branches:
      - 'dev'
      - 'feature/*'
    branches-ignore:
      - 'prod'
    tags:
      - 'v*'
    tags-ignore:
      - 'v0.*'
    paths:
      - 'src/**'
      - '**.py'
    paths-ignore:
      - 'README.md'
      - 'docs/**'
jobs:
  test: 
    name: display 
    runs-on: ubuntu-latest 
    steps:
      - name: this is just for demonostration
        run: echo "this is just for demo"

  